import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state using a type
interface AuthState {
    isOpen:boolean
    isBookingForm:boolean
 
}

const initialState: AuthState = {
    isOpen:false,
    isBookingForm:false

};

const globalSlice = createSlice({
  name: 'global',
  initialState,
  reducers: {
    openAdminSlide:(state)=>{
       state.isOpen=true 
    },
    closeAdminSlide:(state)=>{
        state.isOpen = false

    },
    openBookingForm:(state)=>{
       state.isBookingForm=true 
    },
    closeBookingForm:(state)=>{
        state.isBookingForm = false

    }

    
  
   
  },
});

// Export the actions generated by the slice
export const { openAdminSlide,closeAdminSlide,openBookingForm,closeBookingForm } = globalSlice.actions;

// Export the reducer to be included in the store
export default globalSlice.reducer;
