import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state using a type
interface AuthState {
    isOpen:boolean
 
}

const initialState: AuthState = {
    isOpen:false

};

const globalSlice = createSlice({
  name: 'global',
  initialState,
  reducers: {
    openAdminSlide:(state)=>{
       state.isOpen=true 
    },
    closeAdminSlide:(state)=>{
        state.isOpen = false

    }
    ,
    
   
  },
});

// Export the actions generated by the slice
export const { openAdminSlide,closeAdminSlide } = globalSlice.actions;

// Export the reducer to be included in the store
export default globalSlice.reducer;
