import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state using a type
interface AuthState {
    isOpen:boolean
    isBookingForm:boolean
 
}

const initialState: AuthState = {
    isOpen:true,
    isBookingForm:false

};

const globalSlice = createSlice({
  name: 'global',
  initialState,
  reducers: {
    toggleAdminSlide: (state) => {
      state.isOpen = !state.isOpen;
    },
    openBookingForm:(state)=>{
       state.isBookingForm=true 
    },
    closeBookingForm:(state)=>{
        state.isBookingForm = false

    }

    
  
   
  },
});

// Export the actions generated by the slice
export const {  toggleAdminSlide,openBookingForm,closeBookingForm } = globalSlice.actions;

// Export the reducer to be included in the store
export default globalSlice.reducer;
